#!/bin/bash

echo "🗄️  Creating PostgreSQL Database for Your Dock Rental App"
echo "========================================================"
echo ""

echo "🚀 Quick Database Setup (2 minutes):"
echo ""
echo "1. 📱 Open this link in your browser:"
echo "   https://vercel.com/dashboard"
echo ""
echo "2. 🔍 Find your project:"
echo "   - Look for 'dock-rental-vercel'"
echo "   - Click on it"
echo ""
echo "3. 🗄️  Create Database:"
echo "   - Click 'Storage' tab"
echo "   - Click 'Create Database'"
echo "   - Choose 'PostgreSQL'"
echo "   - Select region (closest to you)"
echo "   - Click 'Create'"
echo ""
echo "4. ✅ Done! Vercel will automatically:"
echo "   - Add POSTGRES_URL environment variable"
echo "   - Connect it to your project"
echo "   - Make it ready for your app"
echo ""
echo "5. 🚀 Then run this command:"
echo "   curl -X POST https://your-app.vercel.app/api/init \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"action\": \"init-database\"}'"
echo ""
echo "🎯 That's it! Your database will be ready with:"
echo "   - 12 dock slips with your image"
echo "   - User authentication system"
echo "   - Booking management"
echo "   - All data persistence"
echo ""
echo "Need help? The process takes less than 2 minutes!"
