#!/bin/bash

echo "🔒 Dock Rental App Security Setup"
echo "=================================="
echo ""

echo "🚨 CRITICAL: You need to set up environment variables in Vercel Dashboard"
echo ""
echo "Follow these steps:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your dock-rental-vercel project"
echo "3. Go to Settings > Environment Variables"
echo "4. Add the following variables:"
echo ""
echo "   STRIPE_SECRET_KEY=sk_live_your_actual_secret_key_here"
echo "   STRIPE_PUBLISHABLE_KEY=pk_live_your_publishable_key_here"
echo "   REACT_APP_API_URL=https://your-backend-url.vercel.app"
echo ""
echo "⚠️  IMPORTANT:"
echo "- Replace 'your_actual_secret_key_here' with your real Stripe secret key"
echo "- Replace 'your_publishable_key_here' with your real Stripe publishable key"
echo "- Replace 'your-backend-url.vercel.app' with your actual backend URL"
echo ""
echo "🔧 Security fixes applied:"
echo "✅ Removed hardcoded secrets from code"
echo "✅ Added security headers"
echo "✅ Configured CORS properly"
echo "✅ Added Content Security Policy"
echo "✅ Added cache control headers"
echo ""
echo "📋 Next steps:"
echo "1. Set environment variables in Vercel"
echo "2. Deploy your app"
echo "3. Test the payment integration"
echo "4. Monitor for any security issues"
echo ""
echo "📖 For more details, see SECURITY.md"
