#!/bin/bash

echo "🗄️  Setting up PostgreSQL Database for Dock Rental App"
echo "======================================================"
echo ""

echo "📋 Steps to set up your database:"
echo ""
echo "1. 🚀 Create PostgreSQL Database in Vercel:"
echo "   - Go to https://vercel.com/dashboard"
echo "   - Select your dock-rental-vercel project"
echo "   - Go to Storage tab"
echo "   - Click 'Create Database'"
echo "   - Choose PostgreSQL"
echo "   - Select your preferred region"
echo "   - Click 'Create'"
echo ""
echo "2. 🔗 Connect Database to Your Project:"
echo "   - After creating the database, Vercel will automatically"
echo "   - add the POSTGRES_URL environment variable"
echo "   - This will be used by your API to connect to the database"
echo ""
echo "3. 🚀 Deploy Your App:"
echo "   - The database tables will be created automatically"
echo "   - Sample data will be initialized on first deployment"
echo ""
echo "4. ✅ Verify Setup:"
echo "   - Test user registration"
echo "   - Test user login"
echo "   - Test booking creation"
echo "   - Check that data persists across deployments"
echo ""
echo "🔧 Database Schema:"
echo "   - users: User accounts and authentication"
echo "   - slips: Dock slip information and availability"
echo "   - bookings: All booking data and relationships"
echo ""
echo "📊 Sample Data:"
echo "   - 2 sample dock slips"
echo "   - 1 admin user"
echo "   - Ready for real bookings"
echo ""
echo "🔒 Security Features:"
echo "   - Password hashing with SHA-256"
echo "   - SQL injection protection via SQLAlchemy ORM"
echo "   - Environment variable configuration"
echo ""
echo "🚀 Ready to deploy? Run: vercel --prod"
